app:
  author: calculators
  description: Beautiful, lightweight online calculators for finance, health, math and more
  name: WebSpace
  title: Beautiful Calculator Tools
  url: https://webspace.com
logging:
  level:
    com:
      calculators: DEBUG
    org:
      springframework:
        web: DEBUG
seo:
  keywords: calculator, online calculator, mortgage calculator, loan calculator, BMI calculator, finance calculator, math calculator
  og-image: /images/og-image.jpg
server:
  port: 8080
  servlet:
    context-path: /
spring:
  thymeleaf:
    cache: false
    encoding: UTF-8
    mode: HTML
    prefix: classpath:/templates/
    servlet:
      content-type: text/html
    suffix: .html
  web:
    resources:
      cache:
        cachecontrol:
          must-revalidate: true
          no-cache: true
          no-store: true
        period: 0
      static-locations: classpath:/static/

  devtools:
    livereload:
      enabled: true
    restart:
      additional-paths: src/main/resources/static
      enabled: true
      exclude: static/**,templates/**